name: release-on-tag
concurrency:
  group: release-on-tag-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
